// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZthBtn: typeof import('./src/components/zth-btn/index.vue')['default']
    ZthRawDisplayer: typeof import('./src/components/zth-raw-displayer/index.vue')['default']
  }
}

export {}
